name: Spring Boot CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Project
        run: mvn clean install
        working-directory: ./cicd-demo

      - name: Run Tests
        run: mvn test
        working-directory: ./cicd-demo